CC = i586-mingw32msvc-gcc -O2 -Wall -mms-bitfields -mwindows
PKG_CONFIG_PATH = /usr/i586-mingw32msvc/lib/pkgconfig

CFLAGS := $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) \
	pkg-config --cflags gtk+-win32-2.0)
LIBS := $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) \
	pkg-config --libs gtk+-win32-2.0)

crazy-button.exe: crazy-button.c
	$(CC) -o $@ $(CFLAGS) $< $(LIBS)
